/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/asier/robotak/kinect/ros/src/kinect_postures/msg/Move.msg
 *
 */


#ifndef KINECT_POSTURES_MESSAGE_MOVE_H
#define KINECT_POSTURES_MESSAGE_MOVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kinect_postures
{
template <class ContainerAllocator>
struct Move_
{
  typedef Move_<ContainerAllocator> Type;

  Move_()
    : correct(false)
    , inter(0.0)
    , final(0.0)  {
    }
  Move_(const ContainerAllocator& _alloc)
    : correct(false)
    , inter(0.0)
    , final(0.0)  {
    }



   typedef uint8_t _correct_type;
  _correct_type correct;

   typedef float _inter_type;
  _inter_type inter;

   typedef float _final_type;
  _final_type final;




  typedef boost::shared_ptr< ::kinect_postures::Move_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinect_postures::Move_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct Move_

typedef ::kinect_postures::Move_<std::allocator<void> > Move;

typedef boost::shared_ptr< ::kinect_postures::Move > MovePtr;
typedef boost::shared_ptr< ::kinect_postures::Move const> MoveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinect_postures::Move_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinect_postures::Move_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kinect_postures

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'kinect_postures': ['/home/asier/robotak/kinect/ros/src/kinect_postures/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kinect_postures::Move_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinect_postures::Move_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinect_postures::Move_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinect_postures::Move_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinect_postures::Move_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinect_postures::Move_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinect_postures::Move_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59d57f5663409befb47aba2f7a049ecb";
  }

  static const char* value(const ::kinect_postures::Move_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59d57f5663409befULL;
  static const uint64_t static_value2 = 0xb47aba2f7a049ecbULL;
};

template<class ContainerAllocator>
struct DataType< ::kinect_postures::Move_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinect_postures/Move";
  }

  static const char* value(const ::kinect_postures::Move_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinect_postures::Move_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool correct\n\
float32 inter\n\
float32 final\n\
";
  }

  static const char* value(const ::kinect_postures::Move_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinect_postures::Move_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.correct);
      stream.next(m.inter);
      stream.next(m.final);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Move_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinect_postures::Move_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinect_postures::Move_<ContainerAllocator>& v)
  {
    s << indent << "correct: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.correct);
    s << indent << "inter: ";
    Printer<float>::stream(s, indent + "  ", v.inter);
    s << indent << "final: ";
    Printer<float>::stream(s, indent + "  ", v.final);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINECT_POSTURES_MESSAGE_MOVE_H
